Hooks:PostHook(WeaponFactoryTweakData, "create_bonuses", "CAFCWMod_Nepgeary_Init", function(self)
-- M27 IAR
if self.wpn_fps_ass_m27gear then
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m27gear", "wpn_fps_upg_fl_ass_spotter")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_st10", "wpn_fps_upg_o_st10", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_susat", "wpn_fps_upg_o_susat", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_po4", "wpn_fps_upg_o_po4", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m27gear", "wpn_fps_upg_fl_wml")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m27gear", "wpn_fps_shield_m4")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m27gear", "wpn_fps_shield_skin_ftp")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m27gear", "wpn_fps_shield_skin_urban")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_delta_rm55", "wpn_fps_upg_o_45rds", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_eotech552", "wpn_fps_upg_o_eotech552", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m27gear", "wpn_fps_upg_fl_anpeq2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m27gear", "wpn_fps_upg_fl_dbal_d2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m27gear", "wpn_fps_upg_fl_m600p")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m27gear", "wpn_fps_upg_fl_utg")
	self:cafcw_add_to_parts("barrel_ext", "wpn_fps_ass_m27gear", "wpn_fps_upg_ns_ass_smg_tromix")
	self:cafcw_attachment_bundle("ammo", "wpn_fps_ass_m27gear", "_556x45mm", "IncendiaryAmmo_MoreAmmoTypes")
	self:cafcw_attachment_bundle("stock", "wpn_fps_ass_m27gear", "AR15_StockPack")
	self:cafcw_attachment_bundle("stock", "wpn_fps_ass_m27gear", "Stock_Attachment_Pack")
	self:cafcw_attachment_bundle("barrel_ext", "wpn_fps_ass_m27gear", "SneakySuppressorPack", "ARSupp")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_visionking", "wpn_fps_upg_o_visionking", "wpn_fps_ass_m4")
	self:cafcw_add_generic_custom_sights("specter", "wpn_fps_ass_m27gear", "wpn_fps_ass_m4")
	self:cafcw_add_generic_custom_sights("acog", "wpn_fps_ass_m27gear", "wpn_fps_ass_m4")
end
end)