Hooks:PostHook(WeaponFactoryTweakData, "create_bonuses", "CAFCWMod_Matt_Init", function(self)
-- Akimbo UMP
if self.wpn_fps_smg_x_ump then
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_x_ump", "wpn_fps_upg_fl_ass_spotter")
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_x_ump", "wpn_fps_upg_fl_wml")
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_x_ump", "wpn_fps_upg_fl_anpeq2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_x_ump", "wpn_fps_upg_fl_dbal_d2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_x_ump", "wpn_fps_upg_fl_m600p")
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_x_ump", "wpn_fps_upg_fl_utg")
	self:cafcw_add_to_parts("barrel_ext", "wpn_fps_smg_x_ump", "wpn_fps_upg_ns_ass_smg_tromix")
end
-- UMP
if self.wpn_fps_smg_ump then
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_kobra", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_m145", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_pkas", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_coyote", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_acog_rmr", "acog", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_hologram", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_gitsch", "acog", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_zeiss", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_okp7", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_hd33", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_prismatic", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_ump", "wpn_fps_upg_fl_ass_spotter")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_srs", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_hcog", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_reflexholo", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_aog", "acog", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_rmr_riser", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_st10", "wpn_fps_upg_o_st10", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_elo", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_po4", "wpn_fps_upg_o_po4", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_susat", "wpn_fps_upg_o_susat", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_ump", "wpn_fps_upg_fl_wml")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_kemper", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_mepro", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_rusak", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_horzine", "specter", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_eotech552", "wpn_fps_upg_o_eotech552", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_ump", "wpn_fps_upg_fl_anpeq2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_ump", "wpn_fps_upg_fl_dbal_d2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_ump", "wpn_fps_upg_fl_m600p")
	self:cafcw_add_to_parts("gadget", "wpn_fps_smg_ump", "wpn_fps_upg_fl_utg")
	self:cafcw_add_to_parts("barrel_ext", "wpn_fps_smg_ump", "wpn_fps_upg_ns_ass_smg_tromix")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_visionking", "wpn_fps_upg_o_visionking", "wpn_fps_smg_mp5")
	self:cafcw_add_to_parts("sight", "wpn_fps_smg_ump", "wpn_fps_upg_o_pka", "specter", "wpn_fps_smg_mp5")
end
-- Montana 5.56
if self.wpn_fps_ass_yayo then
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_kobra", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_compm4s", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_m145", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_pkas", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_coyote", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_acog_rmr", "acog", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_hologram", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_gitsch", "acog", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_zeiss", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_okp7", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_hd33", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_prismatic", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_yayo", "wpn_fps_upg_fl_ass_spotter")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_srs", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_st10", "wpn_fps_upg_o_st10", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_hcog", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_reflexholo", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_aog", "acog", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_rmr_riser", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_elo", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_po4", "wpn_fps_upg_o_po4", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_yayo", "wpn_fps_upg_fl_wml")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_kemper", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_mepro", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_rusak", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_delta_rm55", "wpn_fps_upg_o_45rds", "wpn_fps_ass_yayo")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_horzine", "specter", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_susat", "wpn_fps_upg_o_susat", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_eotech552", "wpn_fps_upg_o_eotech552", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_yayo", "wpn_fps_upg_fl_anpeq2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_yayo", "wpn_fps_upg_fl_dbal_d2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_yayo", "wpn_fps_upg_fl_m600p")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_yayo", "wpn_fps_upg_fl_utg")
	self:cafcw_add_to_parts("barrel_ext", "wpn_fps_ass_yayo", "wpn_fps_upg_ns_ass_smg_tromix")
	self:cafcw_attachment_bundle("ammo", "wpn_fps_ass_yayo", "_556x45mm", "IncendiaryAmmo_MoreAmmoTypes")
	self:cafcw_attachment_bundle("stock", "wpn_fps_ass_yayo", "AR15_StockPack")
	self:cafcw_attachment_bundle("stock", "wpn_fps_ass_yayo", "Stock_Attachment_Pack")
	self:cafcw_attachment_bundle("barrel_ext", "wpn_fps_ass_yayo", "SneakySuppressorPack", "ARSupp")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_visionking", "wpn_fps_upg_o_visionking", "wpn_fps_ass_contraband")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_yayo", "wpn_fps_upg_o_pka", "specter", "wpn_fps_ass_contraband")
end
end)