Hooks:PostHook(WeaponFactoryTweakData, "create_bonuses", "CAFCWMod_Leon_Init", function(self)
if self.wpn_fps_sho_usas12 then
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_kobra", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_compm4s", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_m145", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_pkas", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_coyote", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_acog_rmr", "acog", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_hologram", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_gitsch", "acog", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_zeiss", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_okp7", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_hd33", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_prismatic", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("gadget", "wpn_fps_sho_usas12", "wpn_fps_upg_fl_ass_spotter")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_srs", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_hcog", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_reflexholo", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_aog", "acog", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_rmr_riser", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_elo", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_po4", "wpn_fps_upg_o_po4", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_susat", "wpn_fps_upg_o_susat", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("gadget", "wpn_fps_sho_usas12", "wpn_fps_upg_fl_wml")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_kemper", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_mepro", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_rusak", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_horzine", "specter", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_sho_usas12", "wpn_fps_upg_o_eotech552", "wpn_fps_upg_o_eotech552", "wpn_fps_sho_aa12", "wpn_fps_sho_usas12_body_rail")
	self:cafcw_add_to_parts("gadget", "wpn_fps_sho_usas12", "wpn_fps_upg_fl_anpeq2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_sho_usas12", "wpn_fps_upg_fl_dbal_d2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_sho_usas12", "wpn_fps_upg_fl_utg")
	self:cafcw_attachment_bundle("ammo", "wpn_fps_sho_usas12", "TaserAmmo_12ga_auto")
end
if self.wpn_fps_shot_prison then
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_kobra", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_compm4s", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_m145", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_pkas", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_coyote", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_acog_rmr", "acog", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_hologram", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_gitsch", "acog", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_zeiss", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_okp7", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_hd33", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_prismatic", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("gadget", "wpn_fps_shot_prison", "wpn_fps_upg_fl_ass_spotter")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_srs", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_hcog", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_reflexholo", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_aog", "acog", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_rmr_riser", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_elo", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_po4", "wpn_fps_upg_o_po4", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_susat", "wpn_fps_upg_o_susat", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("gadget", "wpn_fps_shot_prison", "wpn_fps_upg_fl_wml")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_kemper", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_mepro", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_rusak", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_horzine", "specter", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("sight_rail", "wpn_fps_shot_prison", "wpn_fps_upg_o_eotech552", "wpn_fps_upg_o_eotech552", "wpn_fps_sho_spas12", "wpn_fps_shot_r870_ris_special")
	self:cafcw_add_to_parts("gadget", "wpn_fps_shot_prison", "wpn_fps_upg_fl_anpeq2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_shot_prison", "wpn_fps_upg_fl_dbal_d2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_shot_prison", "wpn_fps_upg_fl_utg")
	self:cafcw_attachment_bundle("ammo", "wpn_fps_shot_prison", "TaserAmmo_12ga_auto")
end
end)