Hooks:PostHook(WeaponFactoryTweakData, "create_bonuses", "CAFCWMod_Nepgeary_Init", function(self)

-- M27 IAR
if self.wpn_fps_ass_m27gear then
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_kobra", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_compm4s", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_m145", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_pkas", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_coyote", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_acog_rmr", "acog", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_hologram", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_zeiss", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_okp7", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_hd33", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_prismatic", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_srs", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_hcog", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_reflexholo", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_aog", "acog", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_rmr_riser", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m27gear", "wpn_fps_upg_fl_ass_spotter")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_st10", "wpn_fps_upg_o_st10", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_elo", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_susat", "wpn_fps_upg_o_susat", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_po4", "wpn_fps_upg_o_po4", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("barrel_ext", "wpn_fps_ass_m27gear", "wpn_fps_ass_ns_g_sup3")
	self:cafcw_add_to_parts("barrel_ext", "wpn_fps_ass_m27gear", "wpn_fps_ass_ns_g_sup4")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m27gear", "wpn_fps_upg_fl_wml")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_kemper", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_mepro", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_rusak", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m27gear", "wpn_fps_riflein556")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m27gear", "wpn_fps_upg_a_taser556")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m27gear", "wpn_fps_shield_m4")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m27gear", "wpn_fps_shield_skin_ftp")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m27gear", "wpn_fps_shield_skin_urban")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_delta_rm55", "wpn_fps_upg_o_45rds", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_horzine", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m27gear", "wpn_fps_upg_o_eotech552", "wpn_fps_upg_o_eotech552", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("stock", "wpn_fps_ass_m27gear", "wpn_fps_upg_m4_s_caastock")
	self:cafcw_add_to_parts("stock", "wpn_fps_ass_m27gear", "wpn_fps_upg_m4_s_caastock_black")
	self:cafcw_add_to_parts("stock", "wpn_fps_ass_m27gear", "wpn_fps_upg_m4_s_hke1")
	self:cafcw_add_to_parts("stock", "wpn_fps_ass_m27gear", "wpn_fps_upg_m4_s_viper")
	self:cafcw_add_to_parts("stock", "wpn_fps_ass_m27gear", "wpn_fps_upg_m4_s_collapsed")
	self:cafcw_add_to_parts("stock", "wpn_fps_ass_m27gear", "wpn_fps_upg_m4_s_pts_col")
	self:cafcw_add_to_parts("stock", "wpn_fps_ass_m27gear", "wpn_fps_upg_m4_s_crane_col")
	self:cafcw_add_to_parts("stock", "wpn_fps_ass_m27gear", "wpn_fps_upg_m4_s_mk46_col")
	self:cafcw_add_to_parts("stock", "wpn_fps_ass_m27gear", "wpn_fps_upg_m4_s_ubr_col")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m27gear", "wpn_fps_upg_fl_anpeq2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m27gear", "wpn_fps_upg_fl_dbal_d2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m27gear", "wpn_fps_upg_fl_utg")
	self:cafcw_add_to_parts("barrel_ext", "wpn_fps_ass_m27gear", "wpn_fps_upg_ns_ass_smg_tromix")
end

end)