Hooks:PostHook(WeaponFactoryTweakData, "create_bonuses", "CAFCWMod_Ellie_Init", function(self)
--FY-JS
if self.wpn_fps_snp_fyjs then
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_kobra", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_compm4s", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_m145", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_pkas", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_1p69", "wpn_fps_upg_o_1p69", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_coyote", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_acog_rmr", "acog", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_hologram", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_gitsch", "acog", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_ta648", "wpn_fps_upg_o_shortdot", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_zeiss", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_deltatitanium", "wpn_fps_upg_o_deltatitanium", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_okp7", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_hd33", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_prismatic", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("gadget", "wpn_fps_snp_fyjs", "wpn_fps_upg_fl_ass_spotter")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_srs", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_csgoscope", "wpn_fps_upg_o_csgoscope", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_hcog", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_reflexholo", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_aog", "acog", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_m4flipup_long", "wpn_fps_upg_o_m4flipup_long", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_mbus_long", "wpn_fps_upg_o_mbus_long", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_scorpionevo_long", "wpn_fps_upg_o_scorpionevo_long", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_troy_long", "wpn_fps_upg_o_troy_long", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_troy_m4_long", "wpn_fps_upg_o_troy_m4_long", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_rmr_riser", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_st10_sniper", "wpn_fps_upg_o_st10_sniper", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_elo", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_po4", "wpn_fps_upg_o_po4", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_susat", "wpn_fps_upg_o_susat", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("gadget", "wpn_fps_snp_fyjs", "wpn_fps_upg_fl_wml")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_kemper", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_rusak", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_ta648rmr", "wpn_fps_upg_o_shortdot", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_delta_rm55", "wpn_fps_upg_o_45rds", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_horzine", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_eotech552", "wpn_fps_upg_o_eotech552", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_kobra", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_kobra", "specter", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("gadget", "wpn_fps_snp_fyjs", "wpn_fps_upg_fl_anpeq2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_snp_fyjs", "wpn_fps_upg_fl_dbal_d2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_snp_fyjs", "wpn_fps_upg_fl_utg")
-- Update v1.68.199
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_xpsg33_magnifier", "wpn_fps_upg_o_xpsg33_magnifier", "wpn_fps_snp_msr")
	self:cafcw_add_to_parts("sight", "wpn_fps_snp_fyjs", "wpn_fps_upg_o_45rds_v2", "wpn_fps_upg_o_45rds_v2", "wpn_fps_snp_msr")
end
--ARX-160
if self.wpn_fps_ass_ar160 then
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_kobra", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_compm4s", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_m145", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_pkas", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_coyote", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_acog_rmr", "acog", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_hologram", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_gitsch", "acog", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_zeiss", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_okp7", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_hd33", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_prismatic", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_ar160", "wpn_fps_upg_fl_ass_spotter")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_srs", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_hcog", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_reflexholo", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_aog", "acog", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_rmr_riser", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_st10", "wpn_fps_upg_o_st10", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_elo", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_po4", "wpn_fps_upg_o_po4", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_susat", "wpn_fps_upg_o_susat", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_ar160", "wpn_fps_upg_fl_wml")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_kemper", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_mepro", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_rusak", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_delta_rm55", "wpn_fps_upg_o_45rds", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_horzine", "specter", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_eotech552", "wpn_fps_upg_o_eotech552", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_ar160", "wpn_fps_upg_fl_anpeq2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_ar160", "wpn_fps_upg_fl_dbal_d2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_ar160", "wpn_fps_upg_fl_utg")
	self:cafcw_add_to_parts("barrel_ext", "wpn_fps_ass_ar160", "wpn_fps_upg_ns_ass_smg_tromix")
	-- Update v1.68.199
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_xpsg33_magnifier", "wpn_fps_upg_o_xpsg33_magnifier", "wpn_fps_ass_amcar")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_ar160", "wpn_fps_upg_o_45rds_v2", "wpn_fps_upg_o_45rds_v2", "wpn_fps_ass_amcar")
	self:cafcw_attachment_bundle("ammo", "wpn_fps_ass_ar160", "IncendiaryAmmo_MoreAmmoTypes_556x45mm")
end
end)