Hooks:PostHook(WeaponFactoryTweakData, "create_bonuses", "CAFCWMod_XxNelsonxX_Init", function(self)
if self.wpn_fps_ass_m4_beowulf then
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_kobra", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_compm4s", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_m145", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_pkas", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_coyote", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_acog_rmr", "acog", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_hologram", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_gitsch", "acog", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_zeiss", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_hd33", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_prismatic", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_ass_spotter")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_srs", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_st10", "wpn_fps_upg_o_st10", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_hcog", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_reflexholo", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_aog", "wpn_fps_upg_o_aog", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_rmr_riser", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_elo", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_po4", "wpn_fps_upg_o_po4", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_susat", "wpn_fps_upg_o_susat", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_kobra", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_wml")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_kemper", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_mepro", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_rusak", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_delta_rm55", "wpn_fps_upg_o_45rds", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_horzine", "specter", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m4_beowulf", "wpn_fps_shield_m4")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m4_beowulf", "wpn_fps_shield_skin_ftp")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m4_beowulf", "wpn_fps_shield_skin_urban")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_eotech552", "wpn_fps_upg_o_eotech552", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_anpeq2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_dbal_d2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_m600p")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_utg")
	self:cafcw_attachment_bundle("stock", "wpn_fps_ass_m4_beowulf", "AR15_StockPack")
	self:cafcw_attachment_bundle("stock", "wpn_fps_ass_m4_beowulf", "Stock_Attachment_Pack")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_visionking", "wpn_fps_upg_o_visionking", "wpn_fps_ass_m4")
	self:cafcw_add_to_parts("sight", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_o_pka", "specter", "wpn_fps_ass_m4")
end
end)